//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcAppDemoEntities : DbContext
    {
        public MvcAppDemoEntities()
            : base("name=MvcAppDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cse_role_userrelation> cse_role_userrelation { get; set; }
        public virtual DbSet<cse_users> cse_users { get; set; }
        public virtual DbSet<cse_rolemaster> cse_rolemaster { get; set; }
    }
}
